version: "3"

services:
  v2ray:
    image: teddysun/xray
    restart: always
    environment:
      - xray.vmess.aead.forced=false
    ports:
      - "1310:1310"
    volumes:
      - ./config/:/etc/xray/
      - ./logs:/var/log/xray/
